# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: neural_protocol.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'neural_protocol.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15neural_protocol.proto\x12\x0fjarvis.protocol\"\\\n\tTelemetry\x12\x13\n\x0b\x63pu_percent\x18\x01 \x01(\x02\x12\x13\n\x0bram_percent\x18\x02 \x01(\x02\x12\x12\n\nmood_score\x18\x03 \x01(\x02\x12\x11\n\tis_online\x18\x04 \x01(\x08\"\x8f\x01\n\x10\x44\x61shboardMetrics\x12\x13\n\x0bunread_mail\x18\x01 \x01(\x05\x12\x15\n\rspotify_track\x18\x02 \x01(\t\x12\x16\n\x0ereminder_count\x18\x03 \x01(\x05\x12\x1c\n\x14leetcode_status_json\x18\x04 \x01(\t\x12\x19\n\x11github_pulse_json\x18\x05 \x01(\t\"o\n\x0eProactiveAlert\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\r\n\x05title\x18\x03 \x01(\t\x12\x0f\n\x07message\x18\x04 \x01(\t\x12\x11\n\ttimestamp\x18\x05 \x01(\x01\x12\x10\n\x08priority\x18\x06 \x01(\t\"\x85\x02\n\x0cNeuralPacket\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\x11\n\ttimestamp\x18\x02 \x01(\x01\x12*\n\x05state\x18\x03 \x01(\x0e\x32\x1b.jarvis.protocol.AgentState\x12-\n\ttelemetry\x18\x04 \x01(\x0b\x32\x1a.jarvis.protocol.Telemetry\x12\x34\n\tdashboard\x18\x05 \x01(\x0b\x32!.jarvis.protocol.DashboardMetrics\x12\x13\n\x0b\x61\x63tive_tool\x18\x06 \x01(\t\x12.\n\x05\x61lert\x18\x07 \x01(\x0b\x32\x1f.jarvis.protocol.ProactiveAlert*U\n\nAgentState\x12\x08\n\x04IDLE\x10\x00\x12\x0c\n\x08THINKING\x10\x01\x12\x0c\n\x08SPEAKING\x10\x02\x12\r\n\tLISTENING\x10\x03\x12\x12\n\x0eTOOL_EXECUTING\x10\x04\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'neural_protocol_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_AGENTSTATE']._serialized_start=659
  _globals['_AGENTSTATE']._serialized_end=744
  _globals['_TELEMETRY']._serialized_start=42
  _globals['_TELEMETRY']._serialized_end=134
  _globals['_DASHBOARDMETRICS']._serialized_start=137
  _globals['_DASHBOARDMETRICS']._serialized_end=280
  _globals['_PROACTIVEALERT']._serialized_start=282
  _globals['_PROACTIVEALERT']._serialized_end=393
  _globals['_NEURALPACKET']._serialized_start=396
  _globals['_NEURALPACKET']._serialized_end=657
# @@protoc_insertion_point(module_scope)
